### ISSUE TITLE
Minga

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#139]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
job de design et production de présentoirs à semences 
## objectif
voir cahier des charges issues #45 
cible de production = 25€/présentoir
l'objectif est aussi de mesurer les tps de réalisation de chaque étapes et de voir où on peut améliorer
## budget
65h, Service design, 55,00 €/h            **3.575,00** 
60pcs, Présentoire, 25,00 €/pc         **1.500,00**
1 forfait, backOffice 10%,  507,50 €           **507,50** 
Total 5582.5
## todolist
- [x] créer les sous tâches de cette issues épique #45 et celle ci.
- [x]  nettoyage du logo opase pour gravure laser (voir pdf dans job/minga) #141 
![image](https://user-images.githubusercontent.com/12049360/30075442-b0cd3ba0-9275-11e7-8598-78fb3f9b2eb5.png)
- [x]  nettoyage du logo pour gravure laser #142 
![image](https://user-images.githubusercontent.com/12049360/30075473-cf766fea-9275-11e7-8c88-4ae9af3e7df7.png)
- [x]  évolution du design de présentoir (avec dewi) mercredi aprem #143 
- [x]  optimisation pour prod, avec dewi vendredi #144 
- [x]  fichier svg prod ready avec gravure
- [x]  achat matériaux? quelle quantité?
- [x]  prod 60x à partir de lundi

### rewards
budget 5500€

**Comment by nicolasdb** [comment]
maquette sachet
![image](https://user-images.githubusercontent.com/12049360/30120556-7cc98b60-9329-11e7-8e32-fa6701ffa7b8.png)

**Comment by DewiBrunet** [comment]
## Update budget 
- ### Service design
3575€ - 170€ (5h x 34€ laser prototype) - 10€ (materiel test) = 3395€
Dewi : 30h 
Nico : 10h30
**Total service design = 40h (83€/h)**

- ### Coût Matériel
Par présentoir :
1,5 Carton = 1,86€ (A vérifier au Schleiper – 1,24€/carton ?)
1 bâton de colle = 0,42€ (au Schleiper 5€/12 bâtons)
30 min de laser = 17€
**Total coût matériel par présentoir = 20€**
Total coût matériel 60 présentoirs = 1200€

- ### Coût production
300€ (1500€ – 1200€ matériel)
**Coût production par présentoir = 5€**


+2 envois par la poste = 30€

**Comment by DewiBrunet** [comment]
## Update ressource à acheter

90 cartons 1 cannelure 70x100cm 
(au Schleiper 1,24€/carton? prix avantageux en grande quantité?)

6 paquets de bâtons de colle 100mm 11,2mm
(au Schleiper 5€/12 batons)

**Comment by nicolasdb** [comment]
Mise à jour:
**Achat,** je pense qu'on peut directement acheter 100 ou 110, c'est bien d'avoir du rab et ça renouvelle le stock utilisé pour les prototypes.
**Tps Nico**
14h pour le design
3h pour l'optimisation
et 2.5h pour le test de prod.
**rendement/cout par pièce**
Je suis passé à 12h d'utilisation laser pour les prototypes.
Je pense qu'on se trompe aussi sur le calcul de tps laser à 34€. 
C'est du tps hô machine comprise qu'il faudrait compter. donc 55€/h
à nous de facturer notre tps à 34€/h. L'écart correspond au coût machine/commun. Sinon on ne prend pas en compte les frais d'utilisation matériels.

**Comment by nicolasdb** [comment]
Note pour le rapport final: 


> Bonjour Nicolas,
> 
> Oui côté montage, on se demandait notamment si la pièce de carton qui est "détachée" de la structure et que vous avez intercalé entre chaque présentoirs avait une utilité et laquelle ?
> 
> Côté tuto... je pensais aussi me filmer (mais faudrait que je trouve quelqu'un pour me filmer) pour que les destinataires soient complètement autonomes dans le montage. Mais si tu as d'autres idées, on prend (d'autant qu'il faut valoriser tout ça dans le cadre de CHIC aussi... voir plus bas !)
> 
> En tous cas, j'aurais besoin de montrer aussi comment "finir le geste" jusqu'au bout (certains sachets de graines, plus épais et un poil plus lourd, devant être posés en bas et d'une certaine manière... On n'a pas eu tous les éléments à temps pour anticiper par exemple que 5 sachets de graines de betterave ne rentrent pas tous dans l'épaisseur prévue.. un détail que seuls les perfectionnistes retiendront ;-)
> 
> Tout le monde sinon trouve ces présentoirs vraiment ingénueux, pratiques, sobres et beaux comme on voulait. La seule "difficulté", en fait, réside dans le choix de carton. Il manquerait un peu de rigidité/solidité... mais comme, en même temps, il doit rester pliable, ça reste un dilemme !
> 
> Sinon, côté "économie" de cette réalisation, et dans la perspective de faire un bilan à valoriser/partager dans le cadre de CHIC... avez vous d'ores et déjà un  bilan à tirer de votre côté ? des problèmes/réussites à partager ? Avez vous pris des images aussi, ou peut-on monter maintenant quelque chose qui évoque cette réalisation ?
> 
> En tous cas je pense qu'il est important de faire valoir, sous une forme ou une autre, non seulement l'apport du design, mais surtout :
> 
> - de la relation entre designer et fabriquant, les échanges que vous avez dû avoir
> 
> - et de la nécessaire prise en considération de toutes les "contraintes" de fabrication/production (choix d'approvisionnement en matériaux, potentialités/adaptation aux outils disponibles, mobilisation de personnes pour produire cette petite série etc...)
> 
> Bref, de bien montrer l'inter-connection des différents savoir-faire, métiers et "entreprises" qu'il est nécessaire de mobiliser autour d'une telle opération... et qui doivent bien penser une juste rétribution du travail de chacun.
> 
> Enfin, enfin, côté facturation, on aurait besoin de 2 factures séparées si possible: 1 pour le design (autre structure que l'Open fab en sorte de la valoriser comme une action CHIC) et 1 pour la production, de l'OPen fab. On pourra verser un premier accompte assez vite... Pourrez-vous attendre un petit peu cependant pour qu'on règle la totalité (on est encore en attente de financement...) ?
> 
> A vite !
>

**Comment by nicolasdb** [comment]
Facture Openfab prod + backoffice: 1500 + 507.5
**2007.5€**
Facture design via smart. 
pour éviter facturation entre partenaire CHIC
**3575€**

**Comment by nicolasdb** [comment]
https://nicolasdb.github.io/post/minga/
Job done et documenté
