### ISSUE TITLE
bug's in mugs

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#174]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
ouverture de leur resto, demande de découpe de menu et enseigne.
## objectif

petits panneaux betonplex, cut profileOut, pocketIN lettre
- [ ] plats
- [ ] tapas
- [ ] boissons

**Comment by nicolasdb** [comment]
okok, 

### Job laser
**Titrage menu:**
Idem qu'au bureau, utiliser le reste de panneau de peuplier (6mm) pour découper des lettres avec typo perso. 
Les zones noircies seront faite à la main au feutre. 

![image](https://user-images.githubusercontent.com/12049360/32172519-33906ac2-bd7c-11e7-8b96-87eb7a5683d3.png)

- [ ] prépa fichier
- [ ] estimation budget
- [ ] organisation du travail pour découpe laser. 
- [ ] déléguer à Dewi pour la découpe au bureau, si dispo.

### Job CNC
**~~plaquettes menu:~~** 
betonplex, 4mm

![image](https://user-images.githubusercontent.com/12049360/32172511-2c00cd38-bd7c-11e7-82e1-463a59c2e826.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/32216099-553a273c-be24-11e7-937a-7a15fd2539db.png)

**Comment by nicolasdb** [comment]
quantité | description
-- | --
1,75 | Prépa fichier (h)
0,72 | MP peuplier 8mm (m²)
0,66 | Découpe laser (h)
