### ISSUE TITLE
Organisation OpenFab : team & task force

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#195]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Beaucoup de choses repose sur @nicolasdb 
On refuse des jobs car le lien client/maker n'est pas fonctionnel.
On veut avoir plus de moyens.

## objectif
Rendre la gestion d'OpenFab plus efficace avec un système plus opérationnel.

## proposition
Création de "team" et de "task force".

Un projet, une demande arrive à OpenFab.
La team gestion la renvois et la renvois à la team correspondante.
La team correspondante accepte l’offre ou non et créé une task force pour réaliser le projet.

![dedbi](https://user-images.githubusercontent.com/25649502/36261784-cafc86f0-1265-11e8-9245-16f48286b926.png)

**team** :
- Objectif N°1 : répondre aux demandes et créer une task force pour réaliser le projet
- Objectif N°2 : prospection
- Composition : 2 à 3 personnes (un référent qui reçoit les demandes et convoque la team)

Teams envisagés : Gestion, vente & service, workshop & event, appel à projets

**task force**
- Objectif : faire le job
- Composition : membres OpenFab

## ressources
Team gestion : Nico et Dewi
Team Appel à projets : Sarah, Chloé, Dewi
Team Vente & service : ??
Team Workshop & event : ??

### rewards
La team reçoit 10% de back-office sur le projet pour s’impliquer dans le devis, suivit client…

**Comment by zuperninja** [comment]
## Prochaines actions 

- [ ] Créer des boites mails pour les membres des team et pour les team
- [ ] Trier les boites mails existantes pour refaire les labels et catégories
- [ ] Tester et itérer


## Avis

AWESOME ! Je surkiffe !

### Team Gestion (aka Boite de Réception)
Je pense que Dewi et Nico ne devrait pas faire partie de la team gestion car trop proche et beaucoup trop talentueux pour faire du secrétariat. Je veux bien me proposer pour checker 1x par jour les boites mails et facebook et renvoyer les jobs aux teams avec une réponse à la personne qui nous contacte. Dewi et Nico pourront me remplacer occasionnellement quand je suis perdue sans internet (ça arrive au moins 2x par mois).

### Les Teams
Chaque Team s'organise après comme ils veulent. On pourra faire un lissage plus tard. Doivent vérifier que tout va bien en task force et l'accompagne. Gère les factures et contact client/task force avec un check sur tout ça régulièrement.

### Task Force
On peut y rentrer et sortir, créer un groupe par projet, etc. Gère la documentation et le job en respectant la qualité OpenFab (héhéhéh)

**Comment by DewiBrunet** [comment]
:) trop bien si tu peux représenter la Team Gestion! Défricher une fois par jour les demandes qu'on reçoit et les renvoyer aux Teams serait très utile. Je me rends pas bien compte de la quantité de messages mais je sais qu'on doit s'améliorer sur le suivi et la réactivité de nos réponses...

- Et du coup limite, @nicolasdb pourrait devenir le référent pour la Team Vente & Service? 
- Moi je veux bien être référent pour la Team Workshop & Event (sachant que je serais l'animateur principal pour fablabmob).

A voir après qui peux rejoindre ces équipes... Lionel sur la partie vente pour des plus gros projets?

- Pour la Team Appel à projets, on s'est déjà réuni une fois et on se revoit bientôt, ça roule, plus qu'à tester de répondre à un projet!

Sur la création de boites mails bonne idée mais est-ce nécessaire si on a un référent par Team qui peut utiliser sa boite mail perso? (ex pour la Team Appel à projets, Chloé est la référente, c'est elle qui reçoit l'info et qui convoque la Team).

**Comment by zuperninja** [comment]
Une dizaine par jour sûrement, parfois plus. Et ce qui est galère c'est de les faire rentrer dans la boucle quand c'est que Nico qui s'en occupe (car pas le temps tout ça). 

Cool cool cool cool :)

Ah oui dans tous les cas vous pouvez utiliser vos boites perso. Ce que j'ai sur celle d'openfab c'est que les mails qui arrivent dessus sont après transmis sur ma perso. Et du coup ça va dans une catégorie (openfab) avec un libellé (github, google business, etc). Après faut paramétrer tout ça quoi :)

**Comment by nicolasdb** [comment]
un truc à faire correspondre aussi, les teams dans github. Un peu comme dans slack, on peut forcer un msg de groupe à la team. par ex: @openfab-lab/website-modo  
https://help.github.com/articles/about-teams/

du coup, un mail/notification est envoyée à chaque membre du groupe. 
Donc, pas besoin de mail supplémentaire. 

Idem, une fois bien organisé, Louis pourra nous aider à configurer un bot qui peut faire un relai automatique, entre slack, github, google, etc... 

L'important est de bien clarifier d'où viens l'info, où on l'a met et où est-ce qu'on la traite, et qui y travaille. Qu'on puisse compter sur le système, éviter les répétions et surtout, si je ou une autre personne délègue une tâche, qu'on puisse vraiment s'y fier. Sinon, ça reste stressant, flou, inefficace et déresponsabilisant. (dans l'ordre que vous voulez)


Il faut aussi un "onboarding" spécifique pour les nouveaux membres de team pour zenhub par exemple. 
@zuperninja tu y a déjà jeté un oeil? c'est le next step à github, pour le managment de tâche.
https://www.zenhub.com/guides#getting-started

**Comment by zuperninja** [comment]
Y a de la place pour tout le monde ! tu m'envoies ton mail pour que je te mettes dans la team (on passe par mail encore en attendant d'avoir plus de gens sur github).

**Comment by satblip** [comment]
slack slack slack slack =D

**Comment by nicolasdb** [comment]
je vous ai d'ailleurs posé une question sur slack :p 
un avis concernant mastodon.

**Comment by satblip** [comment]
je t'ai répondu :-D

**Comment by satblip** [comment]
Btw, si quelqu'un sait me rajouter dans l'organisation github d'openfab, ca me permettrait d'utiliser zenhub (read-only pour le moment 😔)

**Comment by nicolasdb** [comment]
Ha, j'essaie de pas oublier, mais je dois faire ça de mon ordi. J'suis dans un parc là ^^

**Comment by satblip** [comment]
Profite bien !! Rien d'urgent 😉

**Comment by DewiBrunet** [comment]
Proposition d'update sur la gestion des teams  : 

### Team gestion : Anne-Ca, Dewi et Nico
Je trouve que ça fonctionne super bien avec Anne-Ca sur la gestion en ligne des messages et moi sur la gestion locale avec Nico. @zuperninja est-ce que tu vois des points à améliorer? des méthodes à mieux automatiser sur le redispatchement des tâches?

Sachant que Anne-Ca prends un rôle important sur la gestion, je me demande si il serait pas correct de définir un % du backoffice qui lui reviendrait? (si elle transmet une demande mais que quelqu'un d'autre fait le devis elle ne touche rien du backoffice alors qu'elle passe du temps à traiter la demande/faire le suivit...)

### Team Appel à projets : Sarah, Chloé, Dewi + Louis?
Ca a bien fonctionné sur l'appel Pompidup même si on a pas candidaté
Ca roule pour l'appel Next Tech, super input de @satblip qui pourrait rejoindre la team?

Je me demande si on doit pas redéfinir un/une référente (pour l'instant Chloé) et son rôle. Cette team fonctionne bien mais il y a un point crucial sur lequel on a du mal : les deadlines/calendrier! Ca nous a joué un tour sur Pompidup et sur Next Tech ça va être serré. J'estime que le rôle du référent serait notamment de fixer des échéances précises à la team sans lequel l'appel à projet ne peut pas être répondu dans de bonne condition (ex : min 1 mois avant de ce lancer sur un aap, finir la rédaction min 2 semaines avant la deadline...)

### Team Vente & service : Anne-Ca, Navid, Anne-So, Dewi
Je propose une organisation plus informelle pour cette team pour mieux gérer les jobs rapidement. Pour être dans la team, les prérequis c'est : être réactif et savoir générer facture/devis (Anne-So et Navid on eu une initiation la dessus)

1) Anne-Ca avec son rôle de germaine 2.0 reçois les demandes.
2) On créé un groupe message Facebook spécifique à la team où elle poste la demande (et donne une deadline de réponse? si personne réponds sous 2 jours, Anne-Ca fait le devis ou donne réponse négative?)
3) Le premier qui y répond reçoit le loot backoffice et dois trouver quelqu'un pour faire le job (en soit, il a même la priorité si il veux faire le job?)
4) Le cash rentre €€€€€


### Team Workshop & event : Dewi? Louis?
Pour cette team, je pense qu'on a pour l'instant pas assez de demandes pour l'activer réellement.
Si ça rentre dans FabLab Mobile --> ce sera à moi ou Nico de s'en charger.
Sinon (teambuilding, autre) --> post sur le groupe facebook?
Au fil des expériences, on clarifie mieux les prix, on a une liste d'exemple et on peut démarcher/répondre plus facilement et constituer une team.

**Comment by zuperninja** [comment]
Super retour @DewiBrunet. Y a bien moyen de améliorer le flow, surtout en prenant le temps de vous connaitre tous mieux :) Pour moi il faut faciliter l'entrée dans les teams et task force et rassurer les membres dans leurs compétences pour que personne n'hésite à participer.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/44533533-03293d00-a6f6-11e8-9eb8-eedf7b709346.png)

**Comment by zuperninja** [comment]
En cours de clarification par ici : https://github.com/zuperninja/WIP/tree/master/OpenFab/Germaine
