### ISSUE TITLE
[dev] Mise à jour du contenu siteweb +  inscription. 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#263]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

## objectif
Redéfinir le contenu du site web. 
Le message doit s'adresser au grand public, il a pour but de cibler et inviter de nouveaux makers à passer à l'action, cultiver leur joie de faire! Avec comme premier pas, rejoindre un groupe et l'inscription comme membre d'Openfab.
L'asbl est ouverte à tous mais le siteweb doit servir de confirmation (filtre pour nous), il faut que le public puisse très rapidement savoir que c'est bien le club qu'il lui faut, que c'est bien la communauté qui lui correspond et qu'il ou elle ne s'inscrit pas pour être déçu ensuite. 

Je cherche à proposer un site simple au premier coup d'oeil, (théorie des 15sec d'attention) mais qui permet d'aller en profondeur selon les envies de savoir plus. (max 3clics)

à synchroniser avec
- [ ] le contenu du README du [RTFM sur gitbook](https://openfab.gitbook.io/rtfm/)
voir l'issue en cour : https://github.com/openfab-lab/rtfm/issues/2
- [ ] la com facebook
- [ ] la page meetup
https://www.meetup.com/makersbrussels/

### Qu'est-ce qu'on doit y retrouver comme info?

- [ ] le nom, on est bien chez Openfab. Visuel, logo, ... 
- [ ] Bricoler, c’est le yoga des makers (ça fait du bien)
- [ ] Problème? Pourquoi on ne bricole pas plus souvent alors? 
- [ ] Proposition: Un club de geek, recherchant un équilibre entre technologie et écologie. 
- [ ] Openfab = fablab bruxellois, le lien avec l’asbl syntonie. 
- [ ] Le but est d’explorer la relation entre l’humain et son environnement, Openfab explore spécifiquement le lien entre humain et technologie. 
- [ ] L’atelier existe depuis 2012, et est fédéré par sa communauté de membres actifs. 
- [ ] Les membres, les 3 cotisations et comment s’inscrire?
- [ ] Contact (formulaire, l’adresse, etc… )
- [ ] Soutien de la commune, le local 158, c’est super. 

## proposition
https://docs.google.com/document/d/1pb4SnKCSIX3XgDFmLoXqQNkIsq7amJSZHw3Pqak5At0/edit?usp=sharing

## ressources
Gitbook propose maintenant le support du multilangue. 
![image](https://user-images.githubusercontent.com/12049360/81546657-fd1c3980-937a-11ea-9608-89f06ca7c4b9.png)

http://tbtc.fr/sugru-the-joy-of-fix/
![image](https://user-images.githubusercontent.com/12049360/82113085-7b9a2200-9753-11ea-97ef-1236a46724dc.png)

## Resultats
Un site dont on est tous super fier, qui transpire nos valeurs et qui parle au coeur, pas qu'au cerveau. 
Un site qui invite à s'inscrire comme membre et aide à franchir la porte. 
Une procédure d'inscription fluide, qui explique bien ce qu'on propose et ce qu'on attend des membres.
### rewards
On a pas de sous, mais c'est aider et contribuer à notre principale porte d'entrée pour tout le monde. 
C'est pas la meilleure des récompenses? #intrinsicmotivation ^^ :heart:

**Comment by nicolasdb** [comment]
## principe 7 permaculture: Partir des structures d'ensembles pour arriver aux détails

1. Quel est la mission d'Openfab?
1. Qu'est-ce qu'on propose aux membres?
1. Le concept de parcours, que ce soit initiatique, ou une méthode de projet, ou de développement personnel... 


L'importance de la narration, le premier frein est l'imprecision de la proposition ou un débordement d'informations. 
- Quels sont les étapes majeures à présenter? 
Chronologiquement, quelles sont les informations qu'une personne a besoin de savoir en consultant le site. 
Et de notre côté, comment structure t-on ce qu'on propose? Et à quel moment doit-on donner l'information?

## les structures narratives. 
Une structure revient régulièrement dans mes lectures, mes inspirations. Que ce soit en gamification ou en théorie du storytelling. 

C'est le cycle de "hero's journey". 
![image](https://user-images.githubusercontent.com/12049360/81562021-75432900-9394-11ea-9cd2-8dd09ec4ac31.png)
https://www.novel-software.com/blog?article=the-hero%E2%80%99s-journey
https://blog.reedsy.com/heros-journey/

ou encore, la version légèrement simplifiée de Dan Harmon, "the Story Circle".
![image](https://user-images.githubusercontent.com/12049360/81562131-9c015f80-9394-11ea-9e20-5ae336864894.png)
https://blog.reedsy.com/dan-harmon-story-circle/

Alors inspiré de ceux ci, je vois le siteweb comme l'acte 1 du "Héro"
![image](https://user-images.githubusercontent.com/12049360/81562425-1cc05b80-9395-11ea-92e5-007a659303f7.png)
ou selon le "story circle": 
![image](https://user-images.githubusercontent.com/12049360/81562593-69a43200-9395-11ea-865a-a7b4bc892e25.png)

Avec, 
1. homepage = Présentation du problème commun, on veut bricoler mais ... 
Introduction de notre proposition, un aperçu de ce qui est possible, la cause défendue par le collectif.
2. l'invitation à s'inscrire comme membre = call to action! 
_mais il ya encore peut-être des doutes, = Refusal of the Call_
3. le process d'inscription = la rencontre avec un guide, "Meeting the Mentor"

## Une fois membre, c'est l'ACTE 2
Le parcours d'apprentissage vers l'autonomie de skill pour enfin battre son éternel Némésis, le moi-paresseux. 
Mais c'est une autre histoire... 
## L'acte 3, le projet est fini, j'y suis arrivé!
Fierté de soi, satisfaction, accomplissement, puissance et je rentre chez moi et et...  mais et ensuite?

**Comment by nicolasdb** [comment]
Pour l'accueil des nouveaux futur membre lors de l'inscription. 
Ce serai bien d'avoir déjà un personnage qui serve un peu d'animal spirituel, de guide. 
_ça ne peut pas être une personne réelle du lab, non._
On pense à l'ours par défaut, mais lequel? Est-ce qu'on veut déjà transmettre une forme de symbolique?
Le choix du personnage est important parce qu'il n'est pas neutre, parce qu'il donne tout de suite une base à l'imaginaire et on va directement associer un contexte culturel. 

Quelques idées de personnage masquotte, mentor,
1. navid propose clippy de microsoft. Mais non.
![image](https://user-images.githubusercontent.com/12049360/81565009-f2709d00-9398-11ea-8561-3dee4d1475b0.png)
2. Germaine2.0, notre admin virtuelle, mais pas très fun et inspirante comme guide. 
![image](https://user-images.githubusercontent.com/12049360/81565103-1af89700-9399-11ea-8976-e82aef955742.png)
3. Smokey the bear, connu comme masquotte de protection contre les feux de forets aux US. 
C'est pas mal mais donne plus un sentiment de sauveteur, gardien des procédures de safety
![image](https://user-images.githubusercontent.com/12049360/81565333-7165d580-9399-11ea-87cc-5c3e473f635c.png)
4. Wall-e, un robot sympathique. plus proche de l'esprit maker?
![image](https://user-images.githubusercontent.com/12049360/81565483-b2f68080-9399-11ea-8b88-34882cd4e7f9.png)
5. Doug, the dog (UP) parce que "I have just met you and I love you"
![image](https://user-images.githubusercontent.com/12049360/81565559-d4576c80-9399-11ea-85c1-4deed369c8f4.png)

**Comment by nicolasdb** [comment]
ah! on a oublié MacGyver, si c'est pas notre guide spirituel à tous.... qui ce serai?!
![image](https://user-images.githubusercontent.com/12049360/81649741-154e9000-9431-11ea-8af4-38f564a242ce.png)

Même si... est-ce qu'on peut dire qu'il bricole vraiment?

**Comment by nicolasdb** [comment]
Wile E. Coyote?
![image](https://user-images.githubusercontent.com/12049360/81650402-1fbd5980-9432-11ea-9f15-e5d947d34a9f.png)

**Comment by nicolasdb** [comment]
JAke? Because suckin' at something is the first step to being sorta good at something.
![image](https://user-images.githubusercontent.com/12049360/81651147-c570c880-9432-11ea-9d5b-79d1c1390be8.png)

**Comment by nicolasdb** [comment]
## Acte 1: 
Au quotidien, les raisons de bricoler sont diverses. 
Que ce soit pour fabriquer, réparer ou explorer, pour soi ou pour offrir, nous choisissons de bricoler car au fond de nous, ça fait du bien. 
MAIS, en vrai, c'est pas si facile. 
Le manque de place ou d'outillage, la peur de faire des erreurs, de ne pas savoir comment s'y prendre, sont quelques un des freins puissant nous laissant la proie facile à la procrastination. 

How cool it would be if: 
"Internet c'est super, mais ce serait génial si je pouvais rencontrer d'autres gens du quartier, avec qui partager mes idées, de qui m'inspirer ou obtenir des conseils, je pourrais peut-être les aider aussi, on pourrait s'échanger des outils, des astuces."

Et bien, c'est ce que propose Openfab. Au travers d'un lieu mis à disposition par la commune d'Ixelles, nous sommes une communauté de makers, comme toi, qui voulons apporter des solutions à tout ces freins. 
Au travers du groupe, la communauté mutualise de l'outillage, des machines numériques, des composants électroniques, le tout réunis dans un lieu sécurisant où l'on partage nos bonnes pratiques, nos astuces, nos savoir-faire afin que nos idées ne restent pas des idées. 
Hier, tu disais demain. c'est aujourd'hui que tu passe à l'action. 
Inscrit toi! Fait quelque chose!

> `inscription`

welcome, bienvenue, 
alors ça y est!? Ready for action?

**Comment by nicolasdb** [comment]
## Inscription

**Comment by nicolasdb** [comment]
## page 1
Proposition de d'abord proposer les tarifs, ensuite les coordonnées. 
-ACTUAL-
![image](https://user-images.githubusercontent.com/12049360/81712607-16a1ac00-9475-11ea-9781-eb4d991c5052.png)

**Comment by nicolasdb** [comment]
## page 2
-ACTUAL-
![image](https://user-images.githubusercontent.com/12049360/81709869-7ba7d280-9472-11ea-94fc-d5ec0725bdde.png)


~~On veut tout savoir sur toi!~~

> En t'inscrivant à notre association, tu nous donne le droit de conserver tes données et de les utiliser pour te contacter. Nous ne les transmettrons JAMAIS à des tiers, nous non plus on aime pas les spams.

**Comment by nicolasdb** [comment]
## page 3
-ACTUAL-
![image](https://user-images.githubusercontent.com/12049360/81721509-41453200-9480-11ea-8dad-13bf4fe8670d.png)

**Comment by nicolasdb** [comment]
## page 4
-ACTUAL-
![image](https://user-images.githubusercontent.com/12049360/82113217-acc72200-9754-11ea-8b46-c09ad478cebb.png)


Bon, c'est l'étape que tout le monde skip, mais comment faire mieux? 
Comment amener la personne à prendre connaissance indirectement des consignes? 
En racontant une histoire, en parsemant les informations durant le processus? 
En redirigeant vers une session spéciale basic&safety?
Je rêve d'un welcome pack avec un carnet "maker" qui rependrai nos valeurs et des références utiles et importantes. 
https://fieldnotesbrand.com/products/utility

ou encore une vidéo qui montre les accidents, sans être pour autant "faire la leçon"
https://vimeo.com/204925838
 
Voici le lien en question du ROI, tjs en cours d'édition [au travers de cette issue](https://github.com/openfab-lab/conseilAdmin/issues/3). 
https://openfab.gitbook.io/rtfm/gouvernance/code-de-conduite

Il faut aussi y faire référence aux safety
https://github.com/openfab-lab/rtfm/issues/42

**Comment by nicolasdb** [comment]
## Last Step - confirmation
Le bouton confirmation aboutis sur une dernière page, avec ceci:
![image](https://user-images.githubusercontent.com/12049360/82113796-029dc900-9759-11ea-99a4-3c60bc85bd01.png)

`src/views/inscription/confirmation.ejs`

Le mail doit être aussi adapté
https://github.com/openfab-lab/app-membres/wiki/Admin#the-automatic-mailing-after-inscription

> xe texte se trouve dans /src/controllers/inscription/etape4.js#L34-L37, balise text
> 
> ).then(result => {
>     const message = {
>       from: config.email.from,
>       to: result[1][0].email,
>       subject: 'Hello',
>       text: 'Bienvenue chez nous!'
>     };


Il doit être rappeler les conditions de validation de l'inscription. 

![image](https://user-images.githubusercontent.com/12049360/81651147-c570c880-9432-11ea-9d5b-79d1c1390be8.png)

Presque au bout !
- [x] 18+ et choix du tarif
- [x] coordonnées
- [ ] ROI
- [ ] Résponsabilisation
- [ ] preuve de paiment bancaire

**Comment by nicolasdb** [comment]
## Admin
1. Template pdf à fournir pour les attestations? à signer en vrai, ou autre et comment? 
2. Registre? on obtient une liste tirée de la base de donnée du site. 
![image](https://user-images.githubusercontent.com/12049360/82114259-f6ffd180-975b-11ea-8c8f-026add672006.png)
![image](https://user-images.githubusercontent.com/12049360/82114280-139c0980-975c-11ea-912f-892755da0432.png)

Mais est-ce qu'on doit tenir un registre papier? ou en tout cas, comment joindre et consolider un registre avec les coordonnées + les pièces jointes?

**Comment by nicolasdb** [comment]
## Profils membre - Edit page
![image](https://user-images.githubusercontent.com/12049360/82114436-0cc1c680-975d-11ea-9670-47d7b957e088.png)

**Comment by nicolasdb** [comment]
## Le Nudge et le Juice
J'aime bien ces techniques mais j'aimerai communiquer quelque part qu'on l'utilise. 
Sinon, ça donne le sentiment négatif d'être manipulé. 

>Une Brève Histoire du Nudge ㅡ Découvrez l'approche nudge pour changer les comportements
https://www.youtube.com/watch?v=i-SVxDlBgXY

>Comment rendre un jeu plus fun en quelques astuces - Game Anatomy
https://youtu.be/ObPFVopisJ4

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/83530107-927a9b80-a4eb-11ea-9efb-6c6786d2ee61.png)
![image](https://user-images.githubusercontent.com/12049360/83530222-b6d67800-a4eb-11ea-87b0-8058a29b0f16.png)

![image](https://user-images.githubusercontent.com/12049360/83530336-e1c0cc00-a4eb-11ea-8f91-672eb23e3bcc.png)

**Comment by nicolasdb** [comment]
Cher journal, j'ai passé un petit moment à discuter du site avec Arnaud ce matin. 
voici une mise à jour du contenu. 
^^

On a précisé le "Qui sont les membres", "à qui s'adresse le lab" et "par quoi commencer" 
Je pense que ce sera bcp plus clair et logique dans la lecture. 
On a reprit la question des bénévoles qui ne doivent pas être membre mais c'est une proposition pour ceux qui n'ont pas encore de projet de venir participer sans s'engager, voir de l'intérieur comment ça se passe. 

Ensuite, dans la continuité de vouloir être local et que les gens ne s'inscrivent pas pour rien. Une solution simple est proposée. 
Pas d'inscription en ligne. 

Enfin oui mais cachée et nous invitons les gens à venir au lab s'inscrire. Ce qui nous permet d'avoir un premier contact, répondre aux questions et renforcer l'aspect club IRL.

**Comment by nicolasdb** [comment]
![PhiloBear](https://user-images.githubusercontent.com/12049360/88023042-a11b2180-cb30-11ea-889b-bc66c9c93d23.png)

**Comment by nicolasdb** [comment]
## BACK to paper

Proposition à imprimer, faire compléter, encoder dans zoho puis stocker préciseusement. 

---

# Syntonie asbl
#### Art. 03 // notre mission
>Promouvoir la relation étroite et la communication qui existent entre l'environnement naturel, l'humain et les nouvelles technologies par tous les moyens disponibles.
- [ ] **numéro d'inscription :** 
## Inscription nouveau membre adhérent
*à compléter en lettres capitale, 
please and thank you.*
- [ ] **Nom et Prénom :**
- [ ] **+18? Age et genre :** 
- [ ] **Adresse email :**
- [ ] **Téléphone :**
- [ ] **Code postal :**
- [ ]  **Ce que j'aime fabriquer :**
<br><br><br>



## Responsabilisation
1. Par la présente inscription, je déclare  **dégager l'ASBL Syntonie de toute responsabilité en cas d'accident, de vol** de quelque nature que ce soit **ou de dommages** sans aucune exception ni réserve, causés par moi-même ou par autrui, personnes et généralement tout objet et biens quelconques rencontrés dans l'enceinte des locaux de l'OpenFab.

1. Je reconnais avoir **pris connaissance du règlement intérieur** relatif à l'ASBL Syntonie et je m'engage à en respecter toute prescription ainsi que toutes les règles de sécurité y afférant.
En cas de dégradations provoquées aux infrastructures et équipements de l'OpenFab, j'en assumerai les frais financiers correspondants.

1. Je suis informé(e) qu'**il m'appartient de souscrire** personnellement **une assurance responsabilité civile** contre tous les sinistres, accidents, vols, de quelque nature que ce soit, causées par moi-même ou à des tiers dans les locaux de l'association et que mon contrat d’assurance ne mentionne aucune clause contraire à ce que précédemment déclaré. 
Je reconnais à l'association le droit de m'exclure de l’enceinte de ses locaux et de la participation à ses activités en cas de non production de cette assurance

Fait à …………………....... , Le .... / .... / ........ .

Signature précédée de la mention « Lu et approuvé » :

**Comment by nicolasdb** [comment]
## What about RGPD?
Ressource:
http://www.larp.be/wp-content/uploads/2018/05/Fiche_GRPD.pdf

### EXEMPLE
>Cet exemple est repris du site d’un de nos membres et utilisé dans le cadre de l’inscription (de faction) à AVATAR.  http://reve-emotion.be/index.php/events/marble-black-2018/
>**Politique de traitement des données personnelles**

> Vos données personnelles ne seront accessibles qu’aux membres organisateurs affiliés à Rêve-Emotion ASBL.
>  Votre adresse mail servira de moyen de contact privilégié avec l’organisation pour la bonne préparation de l’évènement. 
>  Une case supplémentaire peut être cochée pour marquer votre accord explicite d’être tenu informé de nos activités en dehors de la faction de Marble Black.
>  La date de naissance des participants nous permet d’être au courant de la présence d’enfants et de mineurs au sein de la faction. 
>  Le numéro de GSM nous servira à vous contacter en cas d’urgence ou si un mail ne s’avérait pas adapté. 
>  Vos intolérances ou régime alimentaire particulier, dans le cas d’une inscription à l’intendance, seront communiqués à l’équipe cuisine afin de prévoir un menu adapté.
>  Vos remarques médicales, si vous jugez utile de nous en informer,  nous permettront de réagir de façon adaptée en cas d’urgence et de tenir le responsable médical informé. 
>  Les photos prise par un photographe de la faction (différent des photographes AVATAR) ne seront pas publiées sur facebook et ne seront utilisées qu’à des fins de promotion des activités de l’ASBL (disponibles dans une galerie sur le site web).
 

### Et nous?
Aujourd'hui, On a ceci: 
>En t'inscrivant à notre assiocitation, tu nous donne le droit de conserver tes données et de les utiliser pour te contacter. Nous ne les transmetterons JAMAIS à des tiers, nous non plus on aime pas les spams.

**Politique de traitement des données personnelles**

- [ ] Vos données personnelles ne seront accessibles qu’aux membres organisateurs affiliés à Syntonie ASBL.
- [ ] Votre adresse mail servira de moyen de contact privilégié avec l’organisation.
- [ ] Une case supplémentaire peut être cochée pour marquer votre accord explicite d’être tenu informé de nos activités
- [ ] `La date de naissance des participants nous permet ....?`
- [ ] `Le genre....?`
- [ ] Le numéro de GSM nous servira à vous contacter en cas d’urgence ou si un mail ne s’avérait pas adapté.

**Comment by nicolasdb** [comment]
https://www.etsy.com/sg-en/listing/249742872/ring-binder-birds-wood-organizer-folder?variation0=902216184
![image](https://user-images.githubusercontent.com/12049360/95853072-13c52300-0d55-11eb-83b3-b992314d894e.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/95857043-4a9e3780-0d5b-11eb-81eb-aa4f442b61be.png)

**Comment by nicolasdb** [comment]
Chez schleipper, non imprimé 30€/250p
![image](https://user-images.githubusercontent.com/12049360/96093757-d4b9dd80-0ecc-11eb-93ed-2de2a2bdd220.png)

via flyer, imprimé recto/verso couleur 117€/250p
![image](https://user-images.githubusercontent.com/12049360/96093858-edc28e80-0ecc-11eb-9b92-b350119a4b9f.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/96417290-64bf9600-11f1-11eb-8e0d-11f0da10af21.png)

**Comment by nicolasdb** [comment]
## what about nos assurances? 

Alors du côté de l'asbl nous avons: 
### AG - Assurance R.C. Associations Sportives ou d'Agrément
- Quel est l'objet de la garantie ?
Est assurée la responsabilité civile (1) qui, en raison d'un fait accidentel, est mise à
charge de l'assuré par un membre de l'association ou un tiers qui a subi des dommages
corporels ou matériels du fait de la pratique en amateur des sports ou activités décrits
aux conditions particulières, y compris au cours de réunions d'entraînement ou de
répétitions et à l'occasion de voyages en commun en vue de participer à des concours,
compétitions, festivals, etc.
Est également comprise dans la garantie la responsabilité pour les dommages découlant
des installations et du matériel appartenant à l'association contractante ou aux membres
du comité ou qui leur ont été loués, prêtés ou mis à leur disposition.
Les membres sont considérés comme tiers entre eux.
- A qui est-elle acquise ?
Sont assurés:
  - le preneur;
  - les membres du comité;
  - les membres de l'association.

### AG - Top commerce
Batiment et contenu
![image](https://user-images.githubusercontent.com/12049360/97197298-c6fa3700-17ad-11eb-926e-9e124d194071.png)


### Allianz - administrateurs de société
![image](https://user-images.githubusercontent.com/12049360/97197224-acc05900-17ad-11eb-8d40-f39f010e8e70.png)
